name: Test workflow
on: push
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create a fake .secret file
        run: echo "primary twist rack vendor diagram image used route theme frown either will" > .secret
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Update submodule
        run: git submodule update --init --recursive && git submodule sync
      - name: Create a fake .secret file inside submodule
        run: cd biconomy-paymasters && echo "primary twist rack vendor diagram image used route theme frown either will" > .secret && cd ..
      - name: Install submodules dependencies
        run: cd biconomy-paymasters && yarn install --frozen-lockfile && npx hardhat compile && cd ..
      - name: build after submodule is built
        run: yarn build
      - name: Lint sources
        run:
          yarn run lint 

  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Create a fake .secret file
        run: echo "primary twist rack vendor diagram image used route theme frown either will" > .secret

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update submodule
        run: git submodule update --init --recursive && git submodule sync 

      - name: Create a fake .secret file inside submodule
        run: cd biconomy-paymasters && echo "primary twist rack vendor diagram image used route theme frown either will" > .secret && cd ..

      - name: Install submodules dependencies
        run: cd biconomy-paymasters && yarn install --frozen-lockfile && npx hardhat compile && cd ..

      - name: build after submodule is built
        run: yarn build

      - name: Run Hardhat Tests
        run: yarn test

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: forge-build

      - name: Run Forge tests
        run: |
          forge test -vvv 
        id: forge-test